version: "3"
services:
        app:
                container_name: "python_env"
                build:
                        context: .
                        dockerfile: ./Dockerfile
                image: python_env               
                volumes:
                        - .:/home/python
                tty: true                          
